// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACgQXGBG2S_WmBfzmGJQ8U31Cao1IerI',
    appId: '1:328486525733:android:83316f9f13ce7785dad8cc',
    messagingSenderId: '328486525733',
    projectId: 'tillty-repros',
    storageBucket: 'tillty-repros.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAikNRlkW4UtePk5mrxJDYUxInQdhcq2_g',
    appId: '1:328486525733:ios:71dd01f7abcc9b35dad8cc',
    messagingSenderId: '328486525733',
    projectId: 'tillty-repros',
    storageBucket: 'tillty-repros.appspot.com',
    iosClientId: '328486525733-ntt3curv09q6ugquqpgvcj4m7tp7bf9m.apps.googleusercontent.com',
    iosBundleId: 'com.tillty.repros',
  );
}
